reverse_integer_class_string: reverse_integer_class_string.cpp
	g++ -g -Wall -std=c++11 reverse_integer_class_string.cpp -o reverse_integer_class_string

reverse_integer_class: reverse_integer_class.cpp
	g++ -g -Wall -std=c++11 reverse_integer_class.cpp -o reverse_integer_class